# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* payment_mercado_pago
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 15.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-09-02 14:37+0000\n"
"PO-Revision-Date: 2022-09-02 14:37+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: payment_mercado_pago
#: model_terms:ir.ui.view,arch_db:payment_mercado_pago.payment_acquirer_form
msgid "Access Token"
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_acquirer.py:0
#, python-format
msgid "Could not establish the connection to the API."
msgstr ""

#. module: payment_mercado_pago
#: model:account.payment.method,name:payment_mercado_pago.payment_method_mercado_pago
#: model:ir.model.fields.selection,name:payment_mercado_pago.selection__payment_acquirer__provider__mercado_pago
msgid "Mercado Pago"
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model.fields,field_description:payment_mercado_pago.field_payment_acquirer__mercado_pago_access_token
msgid "Mercado Pago Access Token"
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_transaction.py:0
#, python-format
msgid "No transaction found matching reference %s."
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model,name:payment_mercado_pago.model_payment_acquirer
msgid "Payment Acquirer"
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model,name:payment_mercado_pago.model_account_payment_method
msgid "Payment Methods"
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model,name:payment_mercado_pago.model_payment_transaction
msgid "Payment Transaction"
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model.fields,field_description:payment_mercado_pago.field_payment_acquirer__provider
msgid "Provider"
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_transaction.py:0
#, python-format
msgid "Received data with invalid status: %s"
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_transaction.py:0
#, python-format
msgid "Received data with missing payment id."
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_transaction.py:0
#, python-format
msgid "Received data with missing reference."
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_transaction.py:0
#, python-format
msgid "Received data with missing status."
msgstr ""

#. module: payment_mercado_pago
#: model:ir.model.fields,help:payment_mercado_pago.field_payment_acquirer__provider
msgid "The Payment Service Provider to use with this acquirer"
msgstr ""

#. module: payment_mercado_pago
#: code:addons/payment_mercado_pago/models/payment_acquirer.py:0
#, python-format
msgid ""
"The communication with the API failed. Mercado Pago gave us the following "
"information: '%s' (code %s)"
msgstr ""
